export const LESSON_BASE_PATH = '/courses/college/6e/grandeurs_mesures/masses';

export const LESSON_CONFIG = {
  id: 'masses',
  sequentialUnlock: true, // déverrouillage séquentiel des modules (voir lessonAccess.js)
  title: 'Masses',
  description:
    'Comparer, mesurer, choisir la bonne unité et convertir des masses dans des situations concrètes : du sac mystère au ravitaillement de l’école.',
  level: 'college',
  grade: '6e',
  chapter: 'grandeurs_mesures',
  chapterTitle: 'Grandeurs et mesures',
  totalModules: 7,
  passingScore: 6,
  masteryThreshold: 0.8,
  emoji: '⚖️',
  estimatedDurationMin: 75,
  skills: [
    'Comparer des masses à l’aide d’une balance',
    'Choisir une unité de masse adaptée à une situation',
    'Lire une masse sur une balance à affichage',
    'Comprendre les relations entre mg, g, kg et t',
    'Convertir une masse en comprenant pourquoi la valeur change',
    'Estimer et résoudre des problèmes de masse',
  ],
  teachingScope: {
    include: ['Unités de masse (kg, g, mg, tonne)', 'Conversions'],
    exclude: ['Unités de force', 'Newtons', 'Densité', 'Relation masse-volume'],
  },
  modules: [
    { id: '01', number: 1, slug: 'sac-mystere', path: `${LESSON_BASE_PATH}/sac-mystere`,
      title: 'Mission : le sac mystère', desc: 'Un crayon, une pomme, un cartable, un vélo : lequel est le plus lourd ?',
      color: 'indigo', style: 'featured', estimatedMin: 8, difficulty: 1, actionText: 'Démarrer',
      stage: 'trigger', teachesLearningPointIds: ['6e_masses_P1'] },
    { id: '02', number: 2, slug: 'choisir-unite', path: `${LESSON_BASE_PATH}/choisir-unite`,
      title: 'Choisir la bonne unité', desc: 'mg, g, kg, t : quatre unités pour quatre échelles de masse.',
      color: 'sky', style: 'featured', estimatedMin: 9, difficulty: 1, actionText: 'Choisir',
      stage: 'discovery', teachesLearningPointIds: ['6e_masses_P2'] },
    { id: '03', number: 3, slug: 'comparer-mesurer', path: `${LESSON_BASE_PATH}/comparer-mesurer`,
      title: 'Comparer et mesurer', desc: 'La balance à deux plateaux, puis la balance à affichage.',
      color: 'emerald', style: 'featured', estimatedMin: 10, difficulty: 2, actionText: 'Peser',
      stage: 'manipulation', teachesLearningPointIds: ['6e_masses_P1', '6e_masses_P3'] },
    { id: '04', number: 4, slug: 'relations-unites', path: `${LESSON_BASE_PATH}/relations-unites`,
      title: 'Construire les relations', desc: 'Empiler des blocs de 100 g jusqu’à former 1 kg.',
      color: 'violet', style: 'featured', estimatedMin: 10, difficulty: 2, actionText: 'Construire',
      stage: 'manipulation', teachesLearningPointIds: ['6e_masses_P4'] },
    { id: '05', number: 5, slug: 'conversions', path: `${LESSON_BASE_PATH}/conversions`,
      title: 'Convertir les masses', desc: 'Passer d’une unité à l’autre en comprenant pourquoi le nombre change.',
      color: 'rose', style: 'featured', estimatedMin: 11, difficulty: 3, actionText: 'Convertir',
      stage: 'formalization', teachesLearningPointIds: ['6e_masses_P5'] },
    { id: '06', number: 6, slug: 'estimation-problemes', path: `${LESSON_BASE_PATH}/estimation-problemes`,
      title: 'Estimer et résoudre', desc: 'Ordre de grandeur, pièges à unité et problèmes concrets.',
      color: 'amber', style: 'featured', estimatedMin: 11, difficulty: 3, actionText: 'Résoudre',
      stage: 'practice_lab', teachesLearningPointIds: ['6e_masses_P6'] },
    { id: '07', number: 7, slug: 'mission-finale', path: `${LESSON_BASE_PATH}/mission-finale`,
      title: '🏆 Mission finale : le ravitaillement', desc: 'Prépare le goûter de l’école : mobilise tout ce que tu as appris.',
      color: 'amber', style: 'assessment', estimatedMin: 16, difficulty: 4, actionText: 'Relever le défi',
      stage: 'evaluation' },
  ],
};
