export const LESSON_BASE_PATH = '/courses/college/6e/nombres_calculs/nombres-entiers';

export const LESSON_CONFIG = {
  // Aligné sur l'id de coursesData.js : c'est cet id qui sert de clé de
  // progression (smarter_lesson_<id>) et qui pilote la reprise de cours.
  id: 'nombres-entiers',
  sequentialUnlock: true, // déverrouillage séquentiel des modules (voir lessonAccess.js)
  title: 'Nombres entiers',
  description:
    "Comprendre ce qu'est vraiment un grand nombre : construire, lire, écrire, décomposer, comparer, ranger et repérer les entiers.",
  level: 'college',
  grade: '6e',
  chapter: 'nombres_calculs',
  chapterTitle: 'Nombres et Calculs',
  passingScore: 8,
  masteryThreshold: 0.8,
  emoji: '🔢',
  estimatedDurationMin: 129,
  skills: [
    'Lire, écrire, décomposer et recomposer les nombres entiers',
    'Comprendre la valeur de position de chaque chiffre',
    'Comparer, ranger et encadrer des nombres entiers',
    'Repérer un nombre sur une demi-droite graduée',
    'Résoudre des problèmes en interprétant des grands nombres',
  ],
  teachingScope: {
    include: [
      'Lire, écrire, décomposer et recomposer les nombres entiers',
      'Comparer et ranger',
      'Repérer sur une demi-droite graduée',
      'Résolution de problèmes',
    ],
    exclude: ['Nombres relatifs', 'Opérations formelles complexes'],
  },
  modules: [
    {
      id: 'L00-ent',
      number: 0,
      slug: '0',
      path: `${LESSON_BASE_PATH}/0`,
      title: 'Mission de départ',
      desc: 'Un petit diagnostic pour savoir par où commencer — jamais un examen.',
      stage: 'prerequisite_check',
      color: 'teal',
      style: 'diagnostic',
      estimatedMin: 5,
      difficulty: 1,
      actionText: 'Vérifier mes bases',
    },
    {
      id: 'L01-ent',
      number: 1,
      slug: '1',
      path: `${LESSON_BASE_PATH}/1`,
      title: 'Mission : Le coffre aux nombres',
      desc: 'Six quantités, aucune règle donnée : comment savoir laquelle est la plus grande ?',
      stage: 'trigger',
      color: 'indigo',
      style: 'featured',
      estimatedMin: 7,
      difficulty: 1,
      actionText: 'Démarrer',
    },
    {
      id: 'L02-ent',
      number: 2,
      slug: '2',
      path: `${LESSON_BASE_PATH}/2`,
      title: 'Construire les nombres',
      desc: 'Cubes, barres et plaques : fabrique un nombre avec du matériel base 10.',
      stage: 'discovery',
      teachesLearningPointIds: ['6e_nombres-entiers_P1'],
      color: 'emerald',
      style: 'featured',
      estimatedMin: 12,
      difficulty: 1,
      actionText: 'Manipuler',
    },
    {
      id: 'L03-ent',
      number: 3,
      slug: '3',
      path: `${LESSON_BASE_PATH}/3`,
      title: 'Lire et écrire les nombres',
      desc: 'Des mots aux chiffres, des chiffres aux mots, et le rôle des groupes de trois.',
      stage: 'discovery',
      teachesLearningPointIds: ['6e_nombres-entiers_P2'],
      color: 'blue',
      style: 'featured',
      estimatedMin: 12,
      difficulty: 2,
      actionText: 'Démarrer',
    },
    {
      id: 'L04-ent',
      number: 4,
      slug: '4',
      path: `${LESSON_BASE_PATH}/4`,
      title: 'La valeur de chaque chiffre',
      desc: 'Le chiffre 8 ne vaut pas toujours 8. Sa position décide de sa valeur.',
      stage: 'manipulation',
      teachesLearningPointIds: ['6e_nombres-entiers_P3'],
      color: 'violet',
      style: 'featured',
      estimatedMin: 12,
      difficulty: 2,
      actionText: 'Explorer',
    },
    {
      id: 'L05-ent',
      number: 5,
      slug: '5',
      path: `${LESSON_BASE_PATH}/5`,
      title: 'Décomposer et recomposer',
      desc: 'Casser un nombre en morceaux, le reconstruire — et comprendre le rôle du zéro.',
      stage: 'manipulation',
      teachesLearningPointIds: ['6e_nombres-entiers_P4'],
      color: 'sky',
      style: 'featured',
      estimatedMin: 12,
      difficulty: 2,
      actionText: 'Démarrer',
    },
    {
      id: 'L06-ent',
      number: 6,
      slug: '6',
      path: `${LESSON_BASE_PATH}/6`,
      title: 'Comparer les nombres',
      desc: 'Laboratoire de comparaison + chasse aux raisonnements faux.',
      stage: 'formalization',
      teachesLearningPointIds: ['6e_nombres-entiers_P5'],
      color: 'amber',
      style: 'featured',
      estimatedMin: 12,
      difficulty: 3,
      actionText: 'Comparer',
    },
    {
      id: 'L07-ent',
      number: 7,
      slug: '7',
      path: `${LESSON_BASE_PATH}/7`,
      title: 'Ranger et encadrer',
      desc: 'Jeu de rangement, puis encadrements de plus en plus précis.',
      stage: 'formalization',
      teachesLearningPointIds: ['6e_nombres-entiers_P5'],
      color: 'rose',
      style: 'featured',
      estimatedMin: 12,
      difficulty: 3,
      actionText: 'Jouer',
    },
    {
      id: 'L08-ent',
      number: 8,
      slug: '8',
      path: `${LESSON_BASE_PATH}/8`,
      title: 'La demi-droite graduée',
      desc: 'Lire une position, trouver le pas, placer un nombre à la bonne distance.',
      stage: 'practice_lab',
      teachesLearningPointIds: ['6e_nombres-entiers_P6'],
      color: 'cyan',
      style: 'featured',
      estimatedMin: 12,
      difficulty: 3,
      actionText: 'Démarrer',
    },
    {
      id: 'L09-ent',
      number: 9,
      slug: '9',
      path: `${LESSON_BASE_PATH}/9`,
      title: 'Les nombres dans le monde réel',
      desc: 'Population, distances, spectateurs : estimer avant de lire la valeur exacte.',
      stage: 'practice_lab',
      teachesLearningPointIds: ['6e_nombres-entiers_P7'],
      color: 'purple',
      style: 'featured',
      estimatedMin: 8,
      difficulty: 2,
      actionText: 'Explorer',
    },
    {
      id: 'L10-ent',
      number: 10,
      slug: '10',
      path: `${LESSON_BASE_PATH}/10`,
      title: 'Problèmes : choisir et interpréter',
      desc: 'Trois problèmes où il faut comprendre les nombres, pas les calculer.',
      stage: 'practice_lab',
      teachesLearningPointIds: ['6e_nombres-entiers_P7'],
      color: 'slate',
      style: 'featured',
      estimatedMin: 12,
      difficulty: 4,
      actionText: 'Résoudre',
    },
    {
      id: 'L11-ent',
      number: 11,
      slug: '11',
      path: `${LESSON_BASE_PATH}/11`,
      title: '🏆 Le Grand Défi des Nombres',
      desc: 'Boss final, profil de maîtrise et synthèse visuelle.',
      stage: 'evaluation',
      color: 'amber',
      style: 'assessment',
      estimatedMin: 18,
      difficulty: 4,
      actionText: 'Relever le défi',
    },
  ],
};
