export const LESSON_BASE_PATH = '/courses/college/6e/nombres_calculs/nombres-decimaux';

export const LESSON_CONFIG = {
  id: 'nombres-decimaux',
  sequentialUnlock: true, // déverrouillage séquentiel des modules (voir lessonAccess.js)
  // La leçon formalise en continu par sa carte des connaissances : chaque
  // module pose ses briques et se termine sur l'état courant de la carte
  // (docs/architecture/KNOWLEDGE_MAP.md).
  knowledgeMap: true,
  // Connaissances SUPPOSÉES acquises (état A du contrat « connaissances avant
  // la demande ») : la numération entière (valeur d'un chiffre, comparaison
  // d'entiers) et la lecture d'une fraction simple « a parts sur b » —
  // exactement les deux compétences que les cinq questions du module 0
  // mesurent, et rien d'autre. Tout le reste (dixième, centième, fraction
  // décimale, écriture à virgule, valeur de position décimale, écritures
  // équivalentes, comparaison, encadrement, ordre de grandeur) est établi
  // dans la leçon même.
  priorKnowledge: ['numeration-entiere', 'lecture-fraction-simple'],
  title: 'Nombres décimaux',
  description:
    "Comprendre qu'un nombre décimal représente une quantité, et savoir passer d'une écriture à l'autre : fraction décimale, écriture à virgule, valeur de position, droite graduée.",
  level: 'college',
  grade: '6e',
  chapter: 'nombres_calculs',
  chapterTitle: 'Nombres et Calculs',
  totalModules: 12,
  passingScore: 8,
  masteryThreshold: 0.8,
  emoji: '🎯',
  estimatedDurationMin: 89,
  skills: [
    "Partager l'unité en dixièmes, centièmes et millièmes",
    'Relier fraction décimale et écriture à virgule',
    'Comprendre la valeur de position de chaque chiffre',
    'Reconnaître des écritures équivalentes (3,5 = 3,50)',
    'Comparer, ranger et encadrer des nombres décimaux',
    'Repérer un décimal sur une droite graduée',
    "Estimer un ordre de grandeur et vérifier qu'un résultat est raisonnable",
  ],
  teachingScope: {
    include: [
      'Fractions décimales',
      'Écriture à virgule',
      'Lien entre écriture décimale et fraction décimale',
      'Comparer, ranger, repérer sur une droite',
      'Ordre de grandeur',
    ],
    exclude: ['Fractions non décimales comme nombres (réservé à la 5e)'],
  },
  modules: [
    {
      id: '00',
      number: 0,
      slug: 'mission-de-depart',
      path: `${LESSON_BASE_PATH}/mission-de-depart`,
      title: 'Mission de départ',
      desc: 'Un petit diagnostic pour savoir par où commencer — jamais un examen.',
      color: 'teal',
      style: 'diagnostic',
      stage: 'prerequisite_check',
      estimatedMin: 4,
      difficulty: 1,
      actionText: 'Vérifier mes bases',
    },
    {
      id: '01',
      number: 1,
      slug: 'entre-deux-nombres',
      path: `${LESSON_BASE_PATH}/entre-deux-nombres`,
      title: 'Mission : Pourquoi les nombres décimaux ?',
      desc: "Quand les entiers ne suffisent plus : comment dire ce qu'il y a entre 3 et 4 ?",
      color: 'indigo',
      style: 'featured',
      estimatedMin: 11,
      difficulty: 1,
      actionText: 'Démarrer',
      stage: 'trigger',
      teachesLearningPointIds: ['6e_nombres-decimaux_P1'],
    },
    {
      id: '02',
      number: 2,
      slug: 'decouper-unite',
      path: `${LESSON_BASE_PATH}/decouper-unite`,
      title: "Découper l'unité",
      desc: 'Partage une unité en 10, puis en 100 : les dixièmes et les centièmes.',
      color: 'emerald',
      style: 'featured',
      estimatedMin: 8,
      difficulty: 1,
      actionText: 'Manipuler',
      stage: 'discovery',
      teachesLearningPointIds: ['6e_nombres-decimaux_P1'],
    },
    {
      id: '03',
      number: 3,
      slug: 'fractions-decimales',
      path: `${LESSON_BASE_PATH}/fractions-decimales`,
      title: 'Les fractions décimales',
      desc: "Écrire une quantité coloriée sous forme de fraction.",
      color: 'sky',
      style: 'featured',
      estimatedMin: 6,
      difficulty: 2,
      actionText: 'Démarrer',
      stage: 'discovery',
      teachesLearningPointIds: ['6e_nombres-decimaux_P1', '6e_nombres-decimaux_P2'],
    },
    {
      id: '04',
      number: 4,
      slug: 'ecriture-virgule',
      path: `${LESSON_BASE_PATH}/ecriture-virgule`,
      title: "Passer à l'écriture à virgule",
      desc: 'La grande traduction : 37/10 devient 3,7. Et la virgule prend son sens.',
      color: 'blue',
      style: 'featured',
      estimatedMin: 6,
      difficulty: 2,
      actionText: 'Traduire',
      stage: 'manipulation',
      teachesLearningPointIds: ['6e_nombres-decimaux_P2'],
    },
    {
      id: '05',
      number: 5,
      slug: 'valeur-position',
      path: `${LESSON_BASE_PATH}/valeur-position`,
      title: 'La valeur de position',
      desc: 'Laboratoire de valeur : que vaut vraiment chaque chiffre après la virgule ?',
      color: 'violet',
      style: 'featured',
      estimatedMin: 6,
      difficulty: 2,
      actionText: 'Explorer',
      stage: 'manipulation',
      teachesLearningPointIds: ['6e_nombres-decimaux_P3'],
    },
    {
      id: '06',
      number: 6,
      slug: 'ecritures-equivalentes',
      path: `${LESSON_BASE_PATH}/ecritures-equivalentes`,
      title: 'Des écritures équivalentes',
      desc: 'La machine à traduire + le mystère des zéros inutiles : 3,5 = 3,50 ≠ 3,05.',
      color: 'cyan',
      style: 'featured',
      estimatedMin: 6,
      difficulty: 3,
      actionText: 'Démarrer',
      stage: 'formalization',
      teachesLearningPointIds: ['6e_nombres-decimaux_P4'],
    },
    {
      id: '07',
      number: 7,
      slug: 'comparer-ranger',
      path: `${LESSON_BASE_PATH}/comparer-ranger`,
      title: 'Comparer et ranger',
      desc: "Pourquoi 2,4 > 2,37 ? Laboratoire de comparaison et chasse aux erreurs.",
      color: 'amber',
      style: 'featured',
      estimatedMin: 9,
      difficulty: 3,
      actionText: 'Comparer',
      stage: 'formalization',
      teachesLearningPointIds: ['6e_nombres-decimaux_P5'],
    },
    {
      id: '08',
      number: 8,
      slug: 'droite-graduee',
      path: `${LESSON_BASE_PATH}/droite-graduee`,
      title: 'La droite graduée',
      desc: 'Zoom après zoom : de 0—1 à 0,3—0,4, place les décimaux et encadre-les.',
      color: 'rose',
      style: 'featured',
      estimatedMin: 6,
      difficulty: 3,
      actionText: 'Zoomer',
      stage: 'practice_lab',
      teachesLearningPointIds: ['6e_nombres-decimaux_P6'],
    },
    {
      id: '09',
      number: 9,
      slug: 'ordre-grandeur',
      path: `${LESSON_BASE_PATH}/ordre-grandeur`,
      title: 'Ordre de grandeur et estimation',
      desc: '1,98 L, est-ce plutôt 1 L ou 2 L ? Estimer avant de calculer.',
      color: 'purple',
      style: 'featured',
      estimatedMin: 6,
      difficulty: 2,
      actionText: 'Estimer',
      stage: 'practice_lab',
      teachesLearningPointIds: ['6e_nombres-decimaux_P7'],
    },
    {
      id: '10',
      number: 10,
      slug: 'calculs-problemes',
      path: `${LESSON_BASE_PATH}/calculs-problemes`,
      title: 'Calculs et problèmes',
      desc: 'Des décimaux dans la vraie vie : comprendre, estimer, calculer, vérifier.',
      color: 'slate',
      style: 'featured',
      estimatedMin: 6,
      difficulty: 4,
      actionText: 'Résoudre',
      stage: 'practice_lab',
      teachesLearningPointIds: ['6e_nombres-decimaux_P5', '6e_nombres-decimaux_P7'],
    },
    {
      id: '11',
      number: 11,
      slug: 'boss-final',
      path: `${LESSON_BASE_PATH}/boss-final`,
      title: '🏆 Le Laboratoire des Décimaux',
      desc: 'Boss final, profil de maîtrise et synthèse visuelle.',
      color: 'amber',
      style: 'assessment',
      estimatedMin: 15,
      difficulty: 4,
      actionText: 'Relever le défi',
      stage: 'evaluation',
    },
  ],
};
