export const LESSON_BASE_PATH = '/courses/college/6e/nombres_calculs/nombres-decimaux';

export const LESSON_CONFIG = {
  id: 'nombres-decimaux',
  sequentialUnlock: true, // déverrouillage séquentiel des modules (voir lessonAccess.js)
  title: 'Nombres décimaux',
  description:
    "Comprendre qu'un nombre décimal représente une quantité, et savoir passer d'une écriture à l'autre : fraction décimale, écriture à virgule, valeur de position, droite graduée.",
  level: 'college',
  grade: '6e',
  chapter: 'nombres_calculs',
  chapterTitle: 'Nombres et Calculs',
  totalModules: 11,
  passingScore: 8,
  masteryThreshold: 0.8,
  emoji: '🎯',
  estimatedDurationMin: 100,
  skills: [
    "Partager l'unité en dixièmes, centièmes et millièmes",
    'Relier fraction décimale et écriture à virgule',
    'Comprendre la valeur de position de chaque chiffre',
    'Reconnaître des écritures équivalentes (3,5 = 3,50)',
    'Comparer, ranger et encadrer des nombres décimaux',
    'Repérer un décimal sur une droite graduée',
    "Estimer un ordre de grandeur et vérifier qu'un résultat est raisonnable",
  ],
  teachingScope: {
    include: [
      'Fractions décimales',
      'Écriture à virgule',
      'Lien entre écriture décimale et fraction décimale',
      'Comparer, ranger, repérer sur une droite',
      'Ordre de grandeur',
    ],
    exclude: ['Fractions non décimales comme nombres (réservé à la 5e)'],
  },
  modules: [
    {
      id: 'L01-dec',
      number: 1,
      slug: '1',
      path: `${LESSON_BASE_PATH}/1`,
      title: 'Mission : Entre deux nombres',
      desc: "Quand les entiers ne suffisent plus : comment dire ce qu'il y a entre 3 et 4 ?",
      color: 'indigo',
      style: 'featured',
      estimatedMin: 8,
      difficulty: 1,
      actionText: 'Démarrer',
    },
    {
      id: 'L02-dec',
      number: 2,
      slug: '2',
      path: `${LESSON_BASE_PATH}/2`,
      title: "Découper l'unité",
      desc: 'Partage une unité en 10, puis en 100 : les dixièmes et les centièmes.',
      color: 'emerald',
      style: 'featured',
      estimatedMin: 12,
      difficulty: 1,
      actionText: 'Manipuler',
    },
    {
      id: 'L03-dec',
      number: 3,
      slug: '3',
      path: `${LESSON_BASE_PATH}/3`,
      title: 'Les fractions décimales',
      desc: 'Écrire une quantité avec un dénominateur 10, 100 ou 1 000.',
      color: 'sky',
      style: 'featured',
      estimatedMin: 12,
      difficulty: 2,
      actionText: 'Démarrer',
    },
    {
      id: 'L04-dec',
      number: 4,
      slug: '4',
      path: `${LESSON_BASE_PATH}/4`,
      title: "Passer à l'écriture à virgule",
      desc: 'La grande traduction : 37/10 devient 3,7. Et la virgule prend son sens.',
      color: 'blue',
      style: 'featured',
      estimatedMin: 12,
      difficulty: 2,
      actionText: 'Traduire',
    },
    {
      id: 'L05-dec',
      number: 5,
      slug: '5',
      path: `${LESSON_BASE_PATH}/5`,
      title: 'La valeur de position',
      desc: 'Laboratoire de valeur : que vaut vraiment chaque chiffre après la virgule ?',
      color: 'violet',
      style: 'featured',
      estimatedMin: 12,
      difficulty: 2,
      actionText: 'Explorer',
    },
    {
      id: 'L06-dec',
      number: 6,
      slug: '6',
      path: `${LESSON_BASE_PATH}/6`,
      title: 'Des écritures équivalentes',
      desc: 'La machine à traduire + le mystère des zéros inutiles : 3,5 = 3,50 ≠ 3,05.',
      color: 'cyan',
      style: 'featured',
      estimatedMin: 12,
      difficulty: 3,
      actionText: 'Démarrer',
    },
    {
      id: 'L07-dec',
      number: 7,
      slug: '7',
      path: `${LESSON_BASE_PATH}/7`,
      title: 'Comparer et ranger',
      desc: "Pourquoi 2,4 > 2,37 ? Laboratoire de comparaison et chasse aux erreurs.",
      color: 'amber',
      style: 'featured',
      estimatedMin: 14,
      difficulty: 3,
      actionText: 'Comparer',
    },
    {
      id: 'L08-dec',
      number: 8,
      slug: '8',
      path: `${LESSON_BASE_PATH}/8`,
      title: 'La droite graduée',
      desc: 'Zoom après zoom : de 0—1 à 0,3—0,4, place les décimaux et encadre-les.',
      color: 'rose',
      style: 'featured',
      estimatedMin: 14,
      difficulty: 3,
      actionText: 'Zoomer',
    },
    {
      id: 'L09-dec',
      number: 9,
      slug: '9',
      path: `${LESSON_BASE_PATH}/9`,
      title: 'Ordre de grandeur et estimation',
      desc: '1,98 L, est-ce plutôt 1 L ou 2 L ? Estimer avant de calculer.',
      color: 'purple',
      style: 'featured',
      estimatedMin: 10,
      difficulty: 2,
      actionText: 'Estimer',
    },
    {
      id: 'L10-dec',
      number: 10,
      slug: '10',
      path: `${LESSON_BASE_PATH}/10`,
      title: 'Calculs et problèmes',
      desc: 'Des décimaux dans la vraie vie : comprendre, estimer, calculer, vérifier.',
      color: 'slate',
      style: 'featured',
      estimatedMin: 14,
      difficulty: 4,
      actionText: 'Résoudre',
    },
    {
      id: 'L11-dec',
      number: 11,
      slug: '11',
      path: `${LESSON_BASE_PATH}/11`,
      title: '🏆 Le Laboratoire des Décimaux',
      desc: 'Boss final, profil de maîtrise, synthèse visuelle et flash retour.',
      color: 'amber',
      style: 'boss',
      estimatedMin: 18,
      difficulty: 4,
      actionText: 'Relever le défi',
    },
  ],
};
