export const LESSON_BASE_PATH = '/courses/college/6e/nombres_calculs/fractions';

export const LESSON_CONFIG = {
  id: 'fractions',
  sequentialUnlock: true, // déverrouillage séquentiel des modules (voir lessonAccess.js)
  title: 'Fractions et fractions décimales',
  description:
    "Construire le sens de la fraction comme nombre et comme résultat d'un partage, puis relier fractions et décimaux déjà connus.",
  level: 'college',
  grade: '6e',
  chapter: 'nombres_calculs',
  chapterTitle: 'Nombres et Calculs',
  totalModules: 10,
  passingScore: 8,
  masteryThreshold: 0.8,
  emoji: '🍫',
  estimatedDurationMin: 95,
  skills: [
    'Construire une fraction en partageant une unité en parts égales',
    'Comprendre le sens du numérateur et du dénominateur',
    "Trouver une fraction simple d'une quantité",
    'Comprendre la fraction comme quotient (partage)',
    'Placer une fraction sur une demi-droite graduée',
    'Relier fractions et nombres décimaux déjà étudiés',
  ],
  teachingScope: {
    include: [
      'Fractions simples (demi, tiers, quart, dixième)',
      'Fraction partage et quotient dans des cas très simples',
      'Placer sur une demi-droite graduée simple',
    ],
    exclude: ['Opérations sur les fractions', 'Fractions de dénominateurs quelconques'],
  },
  modules: [
    {
      id: 'L01-fr',
      number: 1,
      slug: '1',
      path: `${LESSON_BASE_PATH}/1`,
      title: 'Mission : Le partage impossible',
      desc: "Une tablette, 4 personnes, un partage équitable : comment noter ce que j'ai reçu ?",
      color: 'indigo',
      style: 'featured',
      estimatedMin: 8,
      difficulty: 1,
      actionText: 'Démarrer',
    },
    {
      id: 'L02-fr',
      number: 2,
      slug: '2',
      path: `${LESSON_BASE_PATH}/2`,
      title: 'Construire une fraction',
      desc: 'Partage une unité, prends des parts, observe la fraction apparaître.',
      color: 'emerald',
      style: 'featured',
      estimatedMin: 10,
      difficulty: 1,
      actionText: 'Manipuler',
    },
    {
      id: 'L03-fr',
      number: 3,
      slug: '3',
      path: `${LESSON_BASE_PATH}/3`,
      title: 'Numérateur et dénominateur',
      desc: 'Que raconte chaque nombre de la fraction ?',
      color: 'sky',
      style: 'featured',
      estimatedMin: 10,
      difficulty: 2,
      actionText: 'Explorer',
    },
    {
      id: 'L04-fr',
      number: 4,
      slug: '4',
      path: `${LESSON_BASE_PATH}/4`,
      title: 'Lire et représenter',
      desc: "De l'image à la fraction, de la fraction à l'image.",
      color: 'violet',
      style: 'featured',
      estimatedMin: 10,
      difficulty: 2,
      actionText: 'Démarrer',
    },
    {
      id: 'L05-fr',
      number: 5,
      slug: '5',
      path: `${LESSON_BASE_PATH}/5`,
      title: "Fraction d'une quantité",
      desc: '1/3 de 12 ballons : partager une collection, pas seulement une forme.',
      color: 'amber',
      style: 'featured',
      estimatedMin: 10,
      difficulty: 3,
      actionText: 'Démarrer',
    },
    {
      id: 'L06-fr',
      number: 6,
      slug: '6',
      path: `${LESSON_BASE_PATH}/6`,
      title: 'Fraction et quotient',
      desc: '3 pizzas pour 4 personnes : pourquoi 3 ÷ 4 = 3/4.',
      color: 'rose',
      style: 'featured',
      estimatedMin: 10,
      difficulty: 3,
      actionText: 'Démarrer',
    },
    {
      id: 'L07-fr',
      number: 7,
      slug: '7',
      path: `${LESSON_BASE_PATH}/7`,
      title: 'Fractions simples',
      desc: 'Demi, tiers, quart, dixième : les reconnaître partout.',
      color: 'cyan',
      style: 'featured',
      estimatedMin: 8,
      difficulty: 2,
      actionText: 'Reconnaître',
    },
    {
      id: 'L08-fr',
      number: 8,
      slug: '8',
      path: `${LESSON_BASE_PATH}/8`,
      title: 'Sur la demi-droite graduée',
      desc: 'Une fraction est un nombre : elle a une place précise entre 0 et 1.',
      color: 'blue',
      style: 'featured',
      estimatedMin: 10,
      difficulty: 3,
      actionText: 'Placer',
    },
    {
      id: 'L09-fr',
      number: 9,
      slug: '9',
      path: `${LESSON_BASE_PATH}/9`,
      title: 'Fractions décimales',
      desc: 'Tu connais déjà 0,5 : quel est le lien avec 1/2 ?',
      color: 'purple',
      style: 'featured',
      estimatedMin: 8,
      difficulty: 2,
      actionText: 'Relier',
    },
    {
      id: 'L10-fr',
      number: 10,
      slug: '10',
      path: `${LESSON_BASE_PATH}/10`,
      title: '🏆 La Mission du Partage',
      desc: 'Problèmes, boss final, profil de maîtrise, synthèse et flash retour.',
      color: 'amber',
      style: 'boss',
      estimatedMin: 20,
      difficulty: 4,
      actionText: 'Relever le défi',
    },
  ],
};
