// Fraction Factory — 6e — "fractions": construire le sens complet de la
// fraction. A pizza laboratory reframed as one coherent factory: le partage,
// la construction, le quotient, les fractions du quotidien, la demi-droite
// graduée et le pont vers les décimaux — jusqu'à ce que la fraction émerge
// entièrement de la manipulation. See docs/architecture/LESSON_CONTRACT.md.

export const LESSON_BASE_PATH = '/courses/college/6e/nombres_calculs/fractions';

// Learning Point ids are derived by coursesData.js from the ordered
// `pointsToLearn` list authored for '6e_fractions' — never invent one here.
// The validator parses this file statically, so ids below must be literal
// strings (not identifier references):
//   6e_fractions_P1 — Construire une fraction en partageant une unité en parts égales
//   6e_fractions_P2 — Comprendre le sens du numérateur et du dénominateur
//   6e_fractions_P3 — Trouver une fraction simple d'une quantité
//   6e_fractions_P4 — Placer une fraction sur une demi-droite graduée

export const LESSON_CONFIG = {
  id: 'fractions',
  sequentialUnlock: true,
  // La leçon formalise en continu par sa carte des connaissances : chaque
  // module pose ses briques et se termine sur l'état courant de la carte
  // (docs/architecture/KNOWLEDGE_MAP.md).
  knowledgeMap: true,
  // Connaissances SUPPOSÉES acquises (état A du contrat « connaissances avant
  // la demande ») : le partage équitable au sens courant et les faits de
  // division simples — exactement les deux choses que les cinq questions du
  // module 0 mesurent, et rien d'autre. Tout le reste (part égale au sens
  // mathématique, numérateur, dénominateur, fraction d'une quantité,
  // quotient, placement sur la demi-droite, fraction décimale) est établi
  // dans la leçon même.
  priorKnowledge: ['calcul-numerique', 'tables-multiplication'],
  title: 'Fractions — Construire le sens de la fraction',
  description:
    "Entre dans la Fraction Factory : partage, coupe, sélectionne, découvre la fraction comme quotient, reconnais les fractions simples du quotidien, place-les sur la demi-droite graduée et relie-les aux nombres décimaux déjà connus — pour construire toi-même le sens complet de la fraction.",
  level: 'college',
  grade: '6e',
  chapter: 'nombres_calculs',
  chapterTitle: 'Nombres et Calculs',
  passingScore: 4,
  masteryThreshold: 0.8,
  emoji: '🍕',
  estimatedDurationMin: 88,
  skills: [
    'Partager une pizza en parts rigoureusement égales',
    'Construire une fraction en sélectionnant des parts égales',
    'Comprendre ce que racontent vraiment le numérateur et le dénominateur',
    "Trouver une fraction simple d'une quantité (par exemple 1/3 de 12)",
    'Comprendre la fraction comme résultat d\'un partage (quotient)',
    'Reconnaître les fractions simples du quotidien (demi, tiers, quart, dixième)',
    'Placer une fraction sur une demi-droite graduée',
  ],
  teachingScope: {
    include: [
      'Fractions simples (demi, tiers, quart, dixième)',
      'Fraction comme partage en parts égales',
      'Fraction comme résultat d\'un partage (quotient) dans des cas très simples',
      'Numérateur et dénominateur',
      "Fraction simple d'une quantité",
      'Placer une fraction sur une demi-droite graduée simple',
    ],
    exclude: [
      'Opérations sur les fractions',
      'Fractions de dénominateurs quelconques',
      "Étude complète des fractions décimales et de l'écriture à virgule (réservée à une leçon dédiée aux nombres décimaux) — le module 9 n'en est qu'un pont léger vers ce que l'élève connaît déjà",
    ],
  },
  modules: [
    {
      id: '00',
      number: 0,
      slug: 'mission-de-depart',
      path: `${LESSON_BASE_PATH}/mission-de-depart`,
      title: 'Mission de départ',
      desc: 'Un petit diagnostic pour savoir par où commencer — jamais un examen.',
      color: 'teal',
      style: 'diagnostic',
      stage: 'prerequisite_check',
      estimatedMin: 4,
      difficulty: 1,
      actionText: 'Vérifier mes bases',
    },
    {
      id: '01',
      number: 1,
      slug: 'partage-impossible',
      path: `${LESSON_BASE_PATH}/partage-impossible`,
      title: 'Le partage impossible',
      desc: 'Un partage qui semble impossible... jusqu\'à ce que tu coupes équitablement.',
      stage: 'trigger',
      teachesLearningPointIds: ['6e_fractions_P1'],
      color: 'violet',
      style: 'featured',
      estimatedMin: 7,
      difficulty: 1,
      actionText: 'Entrer dans la Factory',
    },
    {
      id: '02',
      number: 2,
      slug: 'construire-une-fraction',
      path: `${LESSON_BASE_PATH}/construire-une-fraction`,
      title: 'Construire une fraction',
      desc: 'Choisis le nombre de parts, puis construis la fraction toi-même.',
      stage: 'discovery',
      teachesLearningPointIds: ['6e_fractions_P1'],
      color: 'sky',
      style: 'featured',
      estimatedMin: 11,
      difficulty: 2,
      actionText: 'Construire',
    },
    {
      id: '03',
      number: 3,
      slug: 'numerateur-denominateur',
      path: `${LESSON_BASE_PATH}/numerateur-denominateur`,
      title: 'Numérateur et dénominateur',
      desc: 'Ce que racontent vraiment les deux nombres d\'une fraction.',
      stage: 'discovery',
      teachesLearningPointIds: ['6e_fractions_P2'],
      color: 'indigo',
      style: 'featured',
      estimatedMin: 7,
      difficulty: 2,
      actionText: 'Décoder',
    },
    {
      id: '04',
      number: 4,
      slug: 'lire-et-representer',
      path: `${LESSON_BASE_PATH}/lire-et-representer`,
      title: 'Lire et représenter',
      desc: 'Sélectionne des parts égales et regarde la fraction se construire.',
      stage: 'manipulation',
      teachesLearningPointIds: ['6e_fractions_P1', '6e_fractions_P2'],
      color: 'violet',
      style: 'featured',
      estimatedMin: 7,
      difficulty: 2,
      actionText: 'Construire',
    },
    {
      id: '05',
      number: 5,
      slug: 'station-quantite',
      path: `${LESSON_BASE_PATH}/station-quantite`,
      title: 'Station Quantité',
      desc: 'Répartis des parts en groupes égaux pour en prélever une fraction.',
      stage: 'manipulation',
      teachesLearningPointIds: ['6e_fractions_P3'],
      color: 'emerald',
      style: 'featured',
      estimatedMin: 6,
      difficulty: 2,
      actionText: 'Répartir',
    },
    {
      id: '06',
      number: 6,
      slug: 'fraction-quotient',
      path: `${LESSON_BASE_PATH}/fraction-quotient`,
      title: 'Fraction et quotient',
      desc: 'Une fraction peut aussi être le résultat d\'un partage.',
      stage: 'manipulation',
      teachesLearningPointIds: ['6e_fractions_P1'],
      color: 'rose',
      style: 'featured',
      estimatedMin: 9,
      difficulty: 3,
      actionText: 'Partager',
    },
    {
      id: '07',
      number: 7,
      slug: 'fractions-simples',
      path: `${LESSON_BASE_PATH}/fractions-simples`,
      title: 'Fractions simples du quotidien',
      desc: 'Demi, tiers, quart, dixième : reconnais-les dans la vie de tous les jours.',
      stage: 'formalization',
      teachesLearningPointIds: ['6e_fractions_P1', '6e_fractions_P2'],
      color: 'amber',
      style: 'featured',
      estimatedMin: 5,
      difficulty: 2,
      actionText: 'Reconnaître',
    },
    {
      id: '08',
      number: 8,
      slug: 'sur-la-droite-graduee',
      path: `${LESSON_BASE_PATH}/sur-la-droite-graduee`,
      title: 'Sur la demi-droite graduée',
      desc: 'Une fraction est un nombre : place-la sur la demi-droite.',
      stage: 'practice_lab',
      teachesLearningPointIds: ['6e_fractions_P4'],
      color: 'blue',
      style: 'featured',
      estimatedMin: 9,
      difficulty: 3,
      actionText: 'Placer',
    },
    {
      id: '09',
      number: 9,
      slug: 'fractions-decimales',
      path: `${LESSON_BASE_PATH}/fractions-decimales`,
      title: 'Fractions décimales',
      desc: 'Tu connais déjà 0,5 — quel est le lien avec les fractions ?',
      stage: 'practice_lab',
      teachesLearningPointIds: ['6e_fractions_P1'],
      color: 'purple',
      style: 'featured',
      estimatedMin: 7,
      difficulty: 2,
      actionText: 'Relier',
    },
    {
      id: '10',
      number: 10,
      slug: 'la-mission-du-partage',
      path: `${LESSON_BASE_PATH}/la-mission-du-partage`,
      title: '🏆 La Mission du Partage',
      desc: 'Épreuves, profil et synthèse — le bilan final de ce que tu maîtrises.',
      stage: 'evaluation',
      color: 'slate',
      style: 'assessment',
      estimatedMin: 16,
      difficulty: 4,
      actionText: 'Relever le défi',
    },
  ],
};
