// T1 — desktop: lesson index, Module 0 diagnostic, Module 1 (no auto-scroll / no auto-advance).
import { LESSON, launch, newCtx, watchErrors, check, summary, getProgress, SHOT_DIR } from './helpers.mjs';
const errors = [];
const { browser } = await launch();
const ctx = await newCtx(browser);
const page = await ctx.newPage();
watchErrors(page, errors);

await page.goto(LESSON, { waitUntil: 'networkidle' });
check('index: Mission de départ card', await page.getByText('Mission de départ').first().isVisible().catch(() => false));
check('index: module 1 card', await page.getByText('Le coffre aux nombres').first().isVisible().catch(() => false));
await page.screenshot({ path: SHOT_DIR + 'v2-index.png', fullPage: true });

await page.goto(`${LESSON}/0`, { waitUntil: 'networkidle' });
await page.waitForSelector('text=Mission de départ', { timeout: 10000 });
check('m0: nav Module suivant clickable pre-submit', await page.getByRole('button', { name: /Module suivant/ }).last().isEnabled().catch(() => false));
check('m0: 6 question counter', await page.getByText('Question 1 / 6').isVisible().catch(() => false));
check('m0: submit disabled before answers', await page.getByRole('button', { name: 'Voir mon résultat' }).isDisabled().catch(() => false));
await page.getByRole('button', { name: 'Chiffre 5, position Centaines' }).click();
check('m0: silent after q1', !(await page.getByText(/Bonne réponse/).first().isVisible().catch(() => false)));
await page.getByRole('button', { name: '300', exact: true }).click();
await page.getByRole('button', { name: 'Centaines', exact: true }).click();
await page.getByRole('button', { name: /^4.026$/ }).click();
await page.getByRole('button', { name: 'huit mille quatre cent cinq' }).click();
await page.getByRole('button', { name: /^12.500$/ }).click();
const submitBtn = page.getByRole('button', { name: 'Voir mon résultat' });
check('m0: submit enabled after all answered', await submitBtn.isEnabled());
await submitBtn.click();
await page.waitForSelector('text=Ta correction', { timeout: 5000 });
check('m0: score 8 / 10 shown', await page.getByText('8 / 10').first().isVisible().catch(() => false));
check('m0: skill bar Numération', await page.getByText('Numération décimale').first().isVisible().catch(() => false));
check('m0: correction shows Bonne réponse for wrong q', await page.getByText(/Bonne réponse :/).first().isVisible().catch(() => false));
check('m0: CTA pret', await page.getByRole('button', { name: /Je suis prêt/ }).isVisible().catch(() => false));
check('m0: redo button', await page.getByRole('button', { name: 'Refaire le diagnostic' }).isVisible().catch(() => false));
await page.screenshot({ path: SHOT_DIR + 'v2-m0-result.png', fullPage: true });
await page.reload({ waitUntil: 'networkidle' });
await page.waitForSelector('text=Ta correction', { timeout: 8000 });
check('m0: result persists after reload', await page.getByText('8 / 10').first().isVisible().catch(() => false));
await page.getByRole('button', { name: 'Refaire le diagnostic' }).click();
check('m0: redo returns to questions', await page.getByRole('button', { name: 'Voir mon résultat' }).isDisabled().catch(() => false));

await page.goto(`${LESSON}/1`, { waitUntil: 'networkidle' });
await page.waitForSelector('text=Le coffre aux nombres', { timeout: 10000 });
check('m1: step 2 locked initially', (await page.getByText("termine l'étape précédente").count()) === 2);
await page.getByRole('button', { name: /Module suivant/ }).last().click();
await page.waitForTimeout(400);
check('m1: popover lists steps', await page.getByText('À terminer avant de continuer').isVisible().catch(() => false));
check('m1: popover step 1 entry', await page.getByRole('button', { name: /Étape 1 —/ }).isVisible().catch(() => false));
await page.screenshot({ path: SHOT_DIR + 'v2-m1-popover.png' });
await page.getByRole('button', { name: /Module suivant/ }).last().click();
for (const v of ['305.000', '8', '42', '307', '2.450', '18.700']) await page.getByRole('button', { name: new RegExp(`^Placer ${v}$`) }).click();
await page.getByRole('button', { name: 'Vérifier mon rangement' }).click();
await page.waitForTimeout(500);
check('m1: wrong order does NOT solve step1 (discovery mode)', (await page.getByText("termine l'étape précédente").count()) === 2);
for (const v of ['305.000', '8', '42', '307', '2.450', '18.700']) {
  const btn = page.getByRole('button', { name: new RegExp(`^Retirer ${v}$`) }).first();
  if (await btn.isVisible().catch(() => false)) await btn.click();
}
for (const v of ['8', '42', '307', '2.450', '18.700', '305.000']) await page.getByRole('button', { name: new RegExp(`^Placer ${v}$`) }).click();
await page.getByRole('button', { name: 'Vérifier mon rangement' }).click();
await page.waitForTimeout(600);
check('m1: correct order solves step1, step2 unlocked', (await page.getByText("termine l'étape précédente").count()) === 1);
await page.getByRole('button', { name: 'Le premier chiffre, tout seul' }).click();
const yBefore = await page.evaluate(() => window.scrollY);
await page.waitForTimeout(900);
check('m1: step2 wrong shows Bonne réponse', await page.getByText(/Bonne réponse :/).first().isVisible().catch(() => false));
check('m1: step2 wrong still unlocks step3', (await page.getByText("termine l'étape précédente").count()) === 0);
const yAfter = await page.evaluate(() => window.scrollY);
check('m1: NO auto-scroll on step completion', Math.abs(yAfter - yBefore) < 5, `scrollY ${yBefore} → ${yAfter}`);
await page.getByRole('button', { name: /12.000 est le plus grand/ }).click();
await page.waitForTimeout(600);
check('m1: step3 done, PiegeVisuel shown', await page.getByText('Longueur de la barre').isVisible().catch(() => false));
check('m1: NO auto-advance countdown', !(await page.getByText(/Passage automatique|Rester ici|dans \d+ s/).first().isVisible().catch(() => false)));
check('m1: nav next enabled after allDone', await page.getByRole('button', { name: /Module suivant/ }).last().isEnabled().catch(() => false));
await page.waitForTimeout(6000);
check('m1: still on module 1 after 6s (no auto-navigate)', page.url().endsWith('/1'));
await page.screenshot({ path: SHOT_DIR + 'v2-m1-done.png', fullPage: true });
const prog = await getProgress(page);
check('m1: completedModules includes "1"', !!prog?.completedModules?.includes('1'), JSON.stringify(prog));
await page.reload({ waitUntil: 'networkidle' });
await page.waitForSelector('text=Le coffre aux nombres', { timeout: 8000 });
check('m1 revisit: all steps unlocked', (await page.getByText("termine l'étape précédente").count()) === 0);
check('m1 revisit: nav next enabled', await page.getByRole('button', { name: /Module suivant/ }).last().isEnabled().catch(() => false));
check('no console/page errors', errors.length === 0, errors.slice(0, 5).join(' | '));
await browser.close();
process.exit(summary() ? 1 : 0);
