// T4 — desktop: Module 11 Boss Final full flow.
import { LESSON, launch, newCtx, watchErrors, check, summary, getProgress, getXp, seed, SHOT_DIR } from './helpers.mjs';
const errors = [];
const { browser } = await launch();
const ctx = await newCtx(browser);
const page = await ctx.newPage();
watchErrors(page, errors);
await seed(page, ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']);
await page.goto(`${LESSON}/11`, { waitUntil: 'networkidle' });
await page.waitForSelector('text=Le Grand Défi des Nombres');
const tab = (n) => page.getByRole('button', { name: n, exact: true });
check('boss: profil tab locked pre-submit', await tab('Mon profil').isDisabled().catch(() => false));
check('boss: synthèse tab locked pre-submit', await tab('Synthèse').isDisabled().catch(() => false));
check('boss: submit disabled before answers', await page.getByRole('button', { name: 'Valider mes 7 réponses' }).isDisabled().catch(() => false));
check('boss: timer toggle present', await page.getByRole('switch').isVisible().catch(() => false));
await page.getByRole('button', { name: '48 275', exact: true }).click();
await page.waitForTimeout(300);
check('boss: silent after first answer', !(await page.getByText(/Bonne réponse/).first().isVisible().catch(() => false)));
check('boss: timer toggle disabled after first answer', await page.getByRole('switch').isDisabled().catch(() => false));
for (const n of ['5 000', '6 000 + 300 + 7', '105 300 > 105 030', '2 450 < 6 307 < 8 099 < 12 450', '6 300', 'Les deux affirmations sont vraies']) await page.getByRole('button', { name: n, exact: true }).click();
const submit = page.getByRole('button', { name: 'Valider mes 7 réponses' });
check('boss: submit enabled after 7 answers', await submit.isEnabled());
await submit.click();
await page.waitForTimeout(600);
check('boss review: score 6 / 7', await page.getByText('6 / 7').first().isVisible().catch(() => false));
check('boss review: wrong shows Ta réponse', await page.getByText('Ta réponse :').first().isVisible().catch(() => false));
check('boss review: wrong shows Bonne réponse', await page.getByText('Bonne réponse :').first().isVisible().catch(() => false));
await page.screenshot({ path: SHOT_DIR + 'v2-boss-review.png', fullPage: true });
check('boss: xp 120 after submit (6×20, no double-award)', (await getXp(page)) === 120, `xp=${await getXp(page)}`);
let prog = await getProgress(page);
check('boss: completedModules has 11', !!prog?.completedModules?.includes('11'));
check('boss: 6 exercise keys recorded', prog?.completedExercises?.length === 6, `n=${prog?.completedExercises?.length}`);
await page.getByRole('button', { name: /Voir mon profil de maîtrise/ }).click();
await page.waitForTimeout(400);
check('profil: problèmes 🟡', await page.getByText('Encore quelques erreurs').first().isVisible().catch(() => false));
check('profil: revoir module 10 link', await page.getByRole('link', { name: /Revoir le module 10/ }).isVisible().catch(() => false));
check('profil: badges débloqués', await page.getByText('Badges débloqués').isVisible().catch(() => false));
await page.screenshot({ path: SHOT_DIR + 'v2-boss-profil.png', fullPage: true });
await page.getByRole('button', { name: 'Passer à la synthèse →' }).click();
await page.waitForTimeout(400);
check('synthèse: concept central', await page.getByText('UN NOMBRE ENTIER').isVisible().catch(() => false));
check('synthèse: capacités DÉCOMPOSER', await page.getByText('DÉCOMPOSER').first().isVisible().catch(() => false));
await page.screenshot({ path: SHOT_DIR + 'v2-boss-synthese.png', fullPage: true });
await page.reload({ waitUntil: 'networkidle' });
await page.waitForSelector('text=Le Grand Défi des Nombres');
await page.waitForTimeout(600);
check('boss persist: review restored after reload', await page.getByText('6 / 7').first().isVisible().catch(() => false));
check('boss persist: profil tab unlocked', await tab('Mon profil').isEnabled().catch(() => false));
prog = await getProgress(page);
check('boss persist: exercise keys survive reload', prog?.completedExercises?.length === 6, `n=${prog?.completedExercises?.length}`);
await page.getByRole('button', { name: 'Refaire le test' }).click();
await page.waitForTimeout(400);
check('boss redo: quiz vierge', await page.getByRole('button', { name: 'Valider mes 7 réponses' }).isDisabled().catch(() => false));
for (const n of ['48 275', '5 000', '6 000 + 300 + 7', '105 300 > 105 030', '2 450 < 6 307 < 8 099 < 12 450', '6 300', 'La première est vraie, la seconde est fausse']) await page.getByRole('button', { name: n, exact: true }).click();
await page.getByRole('button', { name: 'Valider mes 7 réponses' }).click();
await page.waitForTimeout(600);
check('boss redo: score 7 / 7', await page.getByText('7 / 7').first().isVisible().catch(() => false));
check('boss redo: xp 140 (idempotent + e7)', (await getXp(page)) === 140, `xp=${await getXp(page)}`);
await page.getByRole('button', { name: /Voir mon profil de maîtrise/ }).click();
await page.getByRole('button', { name: 'Passer à la synthèse →' }).click();
await page.waitForTimeout(400);
check('synthèse: master badge 7/7', await page.getByText('Maître des nombres entiers !').isVisible().catch(() => false));
check('no console/page errors', errors.length === 0, errors.slice(0, 5).join(' | '));
await browser.close();
process.exit(summary() ? 1 : 0);
