export const LESSON_BASE_PATH = '/courses/college/6e/grandeurs_mesures/contenances';

export const LESSON_CONFIG = {
  id: 'contenances',
  sequentialUnlock: true, // déverrouillage séquentiel des modules (voir lessonAccess.js)
  title: 'Contenances',
  description:
    'Comparer, mesurer, choisir la bonne unité et convertir des contenances dans des situations concrètes : du verre au bar à jus.',
  level: 'college',
  grade: '6e',
  chapter: 'grandeurs_mesures',
  chapterTitle: 'Grandeurs et mesures',
  totalModules: 7,
  passingScore: 6,
  masteryThreshold: 0.8,
  emoji: '💧',
  estimatedDurationMin: 63,
  skills: [
    'Comparer des contenances en transvasant un liquide',
    'Mesurer une contenance à l’aide d’un récipient gradué',
    'Choisir une unité de contenance adaptée à une situation',
    'Comprendre les relations entre L, dL, cL et mL',
    'Convertir une contenance en comprenant pourquoi la valeur change',
    'Relier 1 L à 1 dm³ et résoudre des problèmes concrets',
  ],
  teachingScope: {
    include: ['Unités de contenance (L, dL, cL, mL)', 'Conversions', 'Lien avec le volume (1 L = 1 dm³)'],
    exclude: ['Calculs de volume de solides quelconques', 'Densité', 'Relation masse-volume'],
  },
  modules: [
    { id: '00', number: 0, slug: 'mission-de-depart', path: `${LESSON_BASE_PATH}/mission-de-depart`,
      title: 'Mission de départ', desc: 'Un petit diagnostic pour savoir par où commencer — jamais un examen.',
      color: 'teal', style: 'diagnostic', stage: 'prerequisite_check',
      estimatedMin: 4, difficulty: 1, actionText: 'Vérifier mes bases' },
    { id: '01', number: 1, slug: 'lequel-contient-le-plus', path: `${LESSON_BASE_PATH}/lequel-contient-le-plus`,
      title: 'Mission : lequel contient le plus ?', desc: 'Une bouteille, une cruche : laquelle contient le plus d’eau ?',
      color: 'indigo', style: 'featured', stage: 'trigger', teachesLearningPointIds: ['6e_contenances_P1'],
      estimatedMin: 8, difficulty: 1, actionText: 'Démarrer' },
    { id: '02', number: 2, slug: 'mesurer-une-contenance', path: `${LESSON_BASE_PATH}/mesurer-une-contenance`,
      title: 'Mesurer une contenance', desc: 'Le litre comme repère : remplir, lire, comparer.',
      color: 'sky', style: 'featured', stage: 'discovery', teachesLearningPointIds: ['6e_contenances_P2'],
      estimatedMin: 9, difficulty: 1, actionText: 'Mesurer' },
    { id: '03', number: 3, slug: 'unites-l-dl-cl-ml', path: `${LESSON_BASE_PATH}/unites-l-dl-cl-ml`,
      title: 'Les unités L, dL, cL, mL', desc: 'Quatre unités pour quatre échelles de contenance.',
      color: 'emerald', style: 'featured', stage: 'discovery', teachesLearningPointIds: ['6e_contenances_P3'],
      estimatedMin: 9, difficulty: 1, actionText: 'Choisir' },
    { id: '04', number: 4, slug: 'construire-les-relations', path: `${LESSON_BASE_PATH}/construire-les-relations`,
      title: 'Construire les relations', desc: 'Partager 1 L en 10 dL, en 100 cL, en 1000 mL.',
      color: 'violet', style: 'featured', stage: 'manipulation', teachesLearningPointIds: ['6e_contenances_P4'],
      estimatedMin: 10, difficulty: 2, actionText: 'Construire' },
    { id: '05', number: 5, slug: 'convertir-les-contenances', path: `${LESSON_BASE_PATH}/convertir-les-contenances`,
      title: 'Convertir les contenances', desc: 'Passer d’une unité à l’autre en comprenant pourquoi le nombre change.',
      color: 'rose', style: 'featured', stage: 'formalization', teachesLearningPointIds: ['6e_contenances_P5'],
      estimatedMin: 11, difficulty: 3, actionText: 'Convertir' },
    { id: '06', number: 6, slug: 'lien-volume-mission-finale', path: `${LESSON_BASE_PATH}/lien-volume-mission-finale`,
      title: '🏆 Le Grand Défi des Contenances', desc: 'Boss final, profil de maîtrise et synthèse — le bar à jus de l’école.',
      color: 'amber', style: 'assessment', stage: 'evaluation',
      estimatedMin: 15, difficulty: 4, actionText: 'Relever le défi' },
  ],
};
