export const LESSON_BASE_PATH = '/courses/college/6e/nombres_calculs/resolution-problemes';

export const LESSON_CONFIG = {
  id: 'resolution-problemes',
  sequentialUnlock: true, // déverrouillage séquentiel des modules (voir lessonAccess.js)
  title: 'Résolution de problèmes',
  description:
    "Développer une démarche complète de résolution : comprendre la situation, choisir une stratégie, calculer, vérifier et communiquer la réponse.",
  level: 'college',
  grade: '6e',
  chapter: 'nombres_calculs',
  chapterTitle: 'Nombres et Calculs',
  totalModules: 11,
  passingScore: 9,
  masteryThreshold: 0.8,
  emoji: '🧭',
  estimatedDurationMin: 100,
  skills: [
    'Comprendre une situation avant de calculer',
    'Extraire les informations utiles et repérer les informations manquantes',
    'Modéliser une situation (schéma, groupes, droite graduée, tableau)',
    'Choisir une stratégie adaptée parmi plusieurs valables',
    'Résoudre des problèmes à une ou plusieurs étapes',
    'Estimer, vérifier et communiquer une réponse complète',
  ],
  teachingScope: {
    include: ['Problèmes à une ou plusieurs étapes', 'Extraire les informations utiles', 'Modéliser une situation simple'],
    exclude: ['Mise en équation formelle'],
  },
  modules: [
    { id: 'L01-rp', number: 1, slug: '1', path: `${LESSON_BASE_PATH}/1`,
      title: 'Mission : Le problème mystère', desc: "6 classes, 24 élèves chacune : découvre la structure avant de calculer.",
      color: 'indigo', style: 'featured', estimatedMin: 9, difficulty: 1, actionText: 'Démarrer' },
    { id: 'L02-rp', number: 2, slug: '2', path: `${LESSON_BASE_PATH}/2`,
      title: 'Comprendre la situation', desc: "Qu'est-ce qui se passe ? L'opération doit émerger du modèle, pas du hasard.",
      color: 'emerald', style: 'featured', estimatedMin: 9, difficulty: 1, actionText: 'Démarrer' },
    { id: 'L03-rp', number: 3, slug: '3', path: `${LESSON_BASE_PATH}/3`,
      title: 'Extraire les informations', desc: "Trier ce qui sert de ce qui ne sert pas — sans se laisser piéger.",
      color: 'sky', style: 'featured', estimatedMin: 9, difficulty: 2, actionText: 'Trier' },
    { id: 'L04-rp', number: 4, slug: '4', path: `${LESSON_BASE_PATH}/4`,
      title: 'Modéliser', desc: 'Groupes, schéma en barres, droite graduée : rendre la relation visible.',
      color: 'violet', style: 'featured', estimatedMin: 10, difficulty: 2, actionText: 'Modéliser' },
    { id: 'L05-rp', number: 5, slug: '5', path: `${LESSON_BASE_PATH}/5`,
      title: 'Choisir une stratégie', desc: 'Plusieurs chemins valables : comparer, pas imposer.',
      color: 'amber', style: 'featured', estimatedMin: 8, difficulty: 2, actionText: 'Comparer' },
    { id: 'L06-rp', number: 6, slug: '6', path: `${LESSON_BASE_PATH}/6`,
      title: 'Problèmes à une étape', desc: 'Combiner, retirer, comparer, grouper, partager — sans étiquette donnée.',
      color: 'rose', style: 'featured', estimatedMin: 10, difficulty: 2, actionText: 'Résoudre' },
    { id: 'L07-rp', number: 7, slug: '7', path: `${LESSON_BASE_PATH}/7`,
      title: 'Problèmes à plusieurs étapes', desc: 'Construire une chaîne de calcul, étape par étape.',
      color: 'cyan', style: 'featured', estimatedMin: 11, difficulty: 3, actionText: 'Enchaîner' },
    { id: 'L08-rp', number: 8, slug: '8', path: `${LESSON_BASE_PATH}/8`,
      title: 'Estimer et vérifier', desc: 'Avant de calculer : à peu près combien ? Après : est-ce cohérent ?',
      color: 'blue', style: 'featured', estimatedMin: 8, difficulty: 2, actionText: 'Vérifier' },
    { id: 'L09-rp', number: 9, slug: '9', path: `${LESSON_BASE_PATH}/9`,
      title: 'Communiquer une réponse', desc: "Un nombre seul n'est pas une réponse complète.",
      color: 'purple', style: 'featured', estimatedMin: 8, difficulty: 2, actionText: 'Rédiger' },
    { id: 'L10-rp', number: 10, slug: '10', path: `${LESSON_BASE_PATH}/10`,
      title: 'Détective des erreurs', desc: 'Repérer la PREMIÈRE erreur dans le raisonnement d\'un élève.',
      color: 'orange', style: 'featured', estimatedMin: 10, difficulty: 3, actionText: 'Enquêter' },
    { id: 'L11-rp', number: 11, slug: '11', path: `${LESSON_BASE_PATH}/11`,
      title: '🏆 La Grande Mission', desc: 'Boss final, profil de maîtrise, synthèse et flash retour.',
      color: 'amber', style: 'boss', estimatedMin: 20, difficulty: 4, actionText: 'Relever le défi' },
  ],
};
