// Les quatre opérations — 6e. Sens des opérations, opérations posées,
// stratégies de calcul mental, choix de l'outil, division euclidienne et
// résolution de problèmes — jusqu'au défi final de "la fête de l'école".
// See docs/architecture/LESSON_CONTRACT.md.

export const LESSON_BASE_PATH = '/courses/college/6e/nombres_calculs/quatre-operations';

// Learning Point ids are derived by coursesData.js from the ordered
// `pointsToLearn` list authored for the '6e_operations' catalogue entry
// (LESSON_CONFIG.id below is 'quatre-operations', which is what the ids are
// actually keyed on) — never invent one here.
// The validator parses this file statically, so ids below must be literal
// strings (not identifier references):
//   6e_quatre-operations_P1 — Comprendre les quatre opérations et leurs situations
//   6e_quatre-operations_P2 — Maîtriser les opérations posées (retenues et échanges)
//   6e_quatre-operations_P3 — Utiliser des stratégies de calcul mental efficaces
//   6e_quatre-operations_P4 — Choisir entre calcul mental, en ligne, posé ou estimation
//   6e_quatre-operations_P5 — Réaliser la division euclidienne et interpréter le reste
//   6e_quatre-operations_P6 — Résoudre des problèmes en choisissant l'opération adaptée

export const LESSON_CONFIG = {
  id: 'quatre-operations',
  sequentialUnlock: true,
  title: 'Les quatre opérations',
  description:
    "Maîtriser l'addition, la soustraction, la multiplication et la division : comprendre le sens de chaque opération, poser un calcul avec retenues et échanges, choisir la bonne stratégie mentale, réaliser une division euclidienne et résoudre des problèmes concrets — jusqu'au défi final.",
  level: 'college',
  grade: '6e',
  chapter: 'nombres_calculs',
  chapterTitle: 'Nombres et Calculs',
  passingScore: 5,
  masteryThreshold: 0.8,
  emoji: '🧮',
  estimatedDurationMin: 119,
  skills: [
    'Comprendre et utiliser les quatre opérations selon la situation',
    'Poser une addition et une soustraction avec retenues et échanges',
    'Utiliser des stratégies de calcul mental efficaces',
    'Choisir entre calcul mental, en ligne, posé ou estimation',
    "Réaliser une division euclidienne et interpréter le reste selon le contexte",
    "Résoudre des problèmes en choisissant l'opération adaptée",
  ],
  teachingScope: {
    include: [
      'Sens des quatre opérations (addition, soustraction, multiplication, division)',
      'Opérations posées avec retenues et échanges',
      'Stratégies de calcul mental',
      "Choix de la méthode de calcul selon la situation",
      'Division euclidienne et interprétation du reste',
      "Résolution de problèmes à une ou plusieurs étapes",
    ],
    exclude: [
      'Nombres relatifs',
      'Priorités opératoires avec parenthèses complexes',
      'Division par un nombre décimal (réservée à la 5e)',
    ],
  },
  modules: [
    {
      id: '00',
      number: 0,
      slug: 'mission-de-depart',
      path: `${LESSON_BASE_PATH}/mission-de-depart`,
      title: 'Mission de départ',
      desc: 'Un petit diagnostic pour savoir par où commencer — jamais un examen.',
      color: 'teal',
      style: 'diagnostic',
      stage: 'prerequisite_check',
      estimatedMin: 4,
      difficulty: 1,
      actionText: 'Vérifier mes bases',
    },
    {
      id: '01',
      number: 1,
      slug: 'le-calculateur-malin',
      path: `${LESSON_BASE_PATH}/le-calculateur-malin`,
      title: 'Mission : Le calculateur malin',
      desc: "Découvrir les quatre familles d'opérations à travers des situations concrètes.",
      stage: 'trigger',
      teachesLearningPointIds: ['6e_quatre-operations_P1'],
      color: 'indigo',
      style: 'featured',
      estimatedMin: 5,
      difficulty: 1,
      actionText: 'Démarrer',
    },
    {
      id: '02',
      number: 2,
      slug: 'additionner',
      path: `${LESSON_BASE_PATH}/additionner`,
      title: 'Additionner : réunir et augmenter',
      desc: 'Manipuler, visualiser sur la droite graduée, poser une addition avec retenue.',
      stage: 'discovery',
      teachesLearningPointIds: ['6e_quatre-operations_P1', '6e_quatre-operations_P2'],
      color: 'emerald',
      style: 'featured',
      estimatedMin: 12,
      difficulty: 1,
      actionText: 'Démarrer',
    },
    {
      id: '03',
      number: 3,
      slug: 'soustraire',
      path: `${LESSON_BASE_PATH}/soustraire`,
      title: 'Soustraire : retirer, comparer, compléter',
      desc: 'Découvrir les trois sens de la soustraction et poser un calcul avec échange.',
      stage: 'discovery',
      teachesLearningPointIds: ['6e_quatre-operations_P1', '6e_quatre-operations_P2'],
      color: 'blue',
      style: 'featured',
      estimatedMin: 12,
      difficulty: 2,
      actionText: 'Démarrer',
    },
    {
      id: '04',
      number: 4,
      slug: 'multiplier',
      path: `${LESSON_BASE_PATH}/multiplier`,
      title: 'Multiplier : construire des groupes',
      desc: 'Groupes égaux et décomposition pour comprendre la multiplication.',
      stage: 'manipulation',
      teachesLearningPointIds: ['6e_quatre-operations_P1'],
      color: 'violet',
      style: 'featured',
      estimatedMin: 12,
      difficulty: 2,
      actionText: 'Démarrer',
    },
    {
      id: '05',
      number: 5,
      slug: 'diviser',
      path: `${LESSON_BASE_PATH}/diviser`,
      title: 'Diviser : partager et regrouper',
      desc: 'Partage équitable, groupement, et sens du reste dans un problème réel.',
      stage: 'manipulation',
      teachesLearningPointIds: ['6e_quatre-operations_P1', '6e_quatre-operations_P5'],
      color: 'amber',
      style: 'featured',
      estimatedMin: 15,
      difficulty: 2,
      actionText: 'Démarrer',
    },
    {
      id: '06',
      number: 6,
      slug: 'operations-posees',
      path: `${LESSON_BASE_PATH}/operations-posees`,
      title: 'Les opérations posées',
      desc: 'Poser une addition, une soustraction, une multiplication ou une division.',
      stage: 'manipulation',
      teachesLearningPointIds: ['6e_quatre-operations_P2'],
      color: 'teal',
      style: 'featured',
      estimatedMin: 10,
      difficulty: 2,
      actionText: 'Démarrer',
    },
    {
      id: '07',
      number: 7,
      slug: 'calcul-mental',
      path: `${LESSON_BASE_PATH}/calcul-mental`,
      title: 'Le laboratoire du calcul malin',
      desc: 'Apprendre des stratégies de calcul mental et les mettre à l\'épreuve.',
      stage: 'formalization',
      teachesLearningPointIds: ['6e_quatre-operations_P3'],
      color: 'cyan',
      style: 'featured',
      estimatedMin: 10,
      difficulty: 2,
      actionText: 'Démarrer',
    },
    {
      id: '08',
      number: 8,
      slug: 'choisir-loutil',
      path: `${LESSON_BASE_PATH}/choisir-loutil`,
      title: "Choisir l'outil de calcul",
      desc: 'Mini-jeu : mental, en ligne, posé ou estimation — la stratégie compte !',
      stage: 'formalization',
      teachesLearningPointIds: ['6e_quatre-operations_P4'],
      color: 'rose',
      style: 'featured',
      estimatedMin: 8,
      difficulty: 2,
      actionText: 'Jouer',
    },
    {
      id: '09',
      number: 9,
      slug: 'resoudre-des-problemes',
      path: `${LESSON_BASE_PATH}/resoudre-des-problemes`,
      title: 'Résoudre des problèmes',
      desc: 'Comprendre → Choisir → Calculer → Vérifier.',
      stage: 'practice_lab',
      teachesLearningPointIds: ['6e_quatre-operations_P5', '6e_quatre-operations_P6'],
      color: 'purple',
      style: 'featured',
      estimatedMin: 12,
      difficulty: 3,
      actionText: 'Démarrer',
    },
    {
      id: '10',
      number: 10,
      slug: 'boss-final-mission-fete',
      path: `${LESSON_BASE_PATH}/boss-final-mission-fete`,
      title: '🏆 Boss Final : Mission Fête',
      desc: "Organise l'événement scolaire en mobilisant les quatre opérations — épreuves, profil et synthèse.",
      stage: 'evaluation',
      color: 'amber',
      style: 'assessment',
      estimatedMin: 18,
      difficulty: 4,
      actionText: 'Relever le défi',
    },
  ],
};
