export const LESSON_BASE_PATH = '/courses/college/6e/nombres_calculs/quatre-operations';

export const LESSON_CONFIG = {
  id: 'quatre-operations',
  sequentialUnlock: true, // déverrouillage séquentiel des modules (voir lessonAccess.js)
  title: 'Les quatre opérations',
  description:
    "Maîtriser l'addition, la soustraction, la multiplication et la division — les comprendre en profondeur, choisir la bonne opération et la bonne stratégie.",
  level: 'college',
  grade: '6e',
  chapter: 'nombres_calculs',
  chapterTitle: 'Nombres et Calculs',
  totalModules: 11,
  passingScore: 8,
  masteryThreshold: 0.8,
  emoji: '🧮',
  estimatedDurationMin: 90,
  skills: [
    'Comprendre et utiliser les quatre opérations',
    'Choisir entre calcul mental, en ligne, posé ou estimation',
    'Réaliser la division euclidienne et interpréter le reste',
    "Résoudre des problèmes en choisissant l'opération adaptée",
  ],
  modules: [
    {
      id: 'L01-4op',
      number: 1,
      slug: '1',
      path: `${LESSON_BASE_PATH}/1`,
      title: 'Mission : Le calculateur malin',
      desc: "Découvrir les quatre familles d'opérations à travers des situations concrètes.",
      color: 'indigo',
      style: 'featured',
      estimatedMin: 5,
      difficulty: 1,
      actionText: 'Démarrer',
    },
    {
      id: 'L02-4op',
      number: 2,
      slug: '2',
      path: `${LESSON_BASE_PATH}/2`,
      title: 'Additionner : réunir et augmenter',
      desc: 'Manipuler, visualiser sur la droite graduée, comprendre les retenues.',
      color: 'emerald',
      style: 'featured',
      estimatedMin: 12,
      difficulty: 1,
      actionText: 'Démarrer',
    },
    {
      id: 'L03-4op',
      number: 3,
      slug: '3',
      path: `${LESSON_BASE_PATH}/3`,
      title: 'Soustraire : retirer, comparer, compléter',
      desc: 'Découvrir les trois sens de la soustraction et maîtriser les échanges.',
      color: 'blue',
      style: 'featured',
      estimatedMin: 12,
      difficulty: 2,
      actionText: 'Démarrer',
    },
    {
      id: 'L04-4op',
      number: 4,
      slug: '4',
      path: `${LESSON_BASE_PATH}/4`,
      title: 'Multiplier : construire des groupes',
      desc: 'Groupes égaux, grille interactive et décomposition pour comprendre la multiplication.',
      color: 'violet',
      style: 'featured',
      estimatedMin: 12,
      difficulty: 2,
      actionText: 'Démarrer',
    },
    {
      id: 'L05-4op',
      number: 5,
      slug: '5',
      path: `${LESSON_BASE_PATH}/5`,
      title: 'Diviser : partager et regrouper',
      desc: 'Partage équitable, groupement et sens du reste dans un problème réel.',
      color: 'amber',
      style: 'featured',
      estimatedMin: 15,
      difficulty: 2,
      actionText: 'Démarrer',
    },
    {
      id: 'L06-4op',
      number: 6,
      slug: '6',
      path: `${LESSON_BASE_PATH}/6`,
      title: 'Les opérations posées',
      desc: 'Tableau de valeur de position, retenues et échanges expliqués visuellement.',
      color: 'sky',
      style: 'featured',
      estimatedMin: 10,
      difficulty: 3,
      actionText: 'Démarrer',
    },
    {
      id: 'L07-4op',
      number: 7,
      slug: '7',
      path: `${LESSON_BASE_PATH}/7`,
      title: 'Le laboratoire du calcul malin',
      desc: 'Apprendre les stratégies de calcul mental et choisir la plus efficace.',
      color: 'cyan',
      style: 'featured',
      estimatedMin: 10,
      difficulty: 2,
      actionText: 'Démarrer',
    },
    {
      id: 'L08-4op',
      number: 8,
      slug: '8',
      path: `${LESSON_BASE_PATH}/8`,
      title: "Choisir l'outil de calcul",
      desc: 'Mini-jeu : mental, en ligne, posé ou estimation — la stratégie compte !',
      color: 'rose',
      style: 'featured',
      estimatedMin: 8,
      difficulty: 2,
      actionText: 'Jouer',
    },
    {
      id: 'L09-4op',
      number: 9,
      slug: '9',
      path: `${LESSON_BASE_PATH}/9`,
      title: 'Résoudre des problèmes',
      desc: 'Comprendre → Choisir → Calculer → Vérifier → Communiquer.',
      color: 'purple',
      style: 'featured',
      estimatedMin: 12,
      difficulty: 3,
      actionText: 'Démarrer',
    },
    {
      id: 'L10-4op',
      number: 10,
      slug: '10',
      path: `${LESSON_BASE_PATH}/10`,
      title: '🏆 Boss Final : Mission Fête',
      desc: "Organise l'événement scolaire en mobilisant les quatre opérations.",
      color: 'amber',
      style: 'boss',
      estimatedMin: 15,
      difficulty: 4,
      actionText: 'Relever le défi',
    },
    {
      id: 'L11-4op',
      number: 11,
      slug: '11',
      path: `${LESSON_BASE_PATH}/11`,
      title: 'Synthèse & Flash Retour',
      desc: 'Fiche visuelle des quatre opérations + 5 questions de réactivation.',
      color: 'slate',
      style: 'assessment',
      estimatedMin: 8,
      difficulty: 2,
      actionText: 'Faire la synthèse',
    },
  ],
};
